[
    {
        "genero": "Crocodylus",
        "especie": "moreletii",
        "subespecie": "acacac",        
        "periodo": "Triasico",
        "epoca": "Temprano",
        "piso": "3",
        "posicionfilo": ["fofofo", "fafafafa"],
        "cuenca": "ischigualasto",
        "formacion": "las vacas",
        "miembro": "craneo",
        "localidad": "san agustin",
        "coordlat": "",
        "coordlong": "",
        "campana": "locardi",
        "nrocampo": "34",
        "descubridor": "",
        "fechadescubrimiento": "20221102",
        "preparador": "roberto",
        "preparacionfecha": "12/03/2021",
        "armario1":"",
        "estante1desde":"",
        "estante1hasta":"",
        "armario2":"",
        "estante2desde":"",
        "estante2hasta":"",
        "partesesqueletales": [
            "dsfdf",
            "fsdfds",
            "fjhtkhjk",
            "oñioñi"
        ],
        "comentario": "eso",
        "imagen": "nada",
        "URL": "lalala.com"
       
    },
    {
        "especimenNumero":"2",
        "genero": "Crocodylus",
        "especie": "acutus",
        "periodo": "Triasico",
        "epoca": "Tardio",
        "piso": "3",
        "posicionFilo": [
            "",
            "",
            ""
        ],
        "cuenca": "ischigualasto",
        "formacion": "los toros",
        "miembro": "craneo",
        "localidad": "san agustin",
        "cordUtm": "",
        "cordGeo": "",
        "campaña": "locardi",
        "descubridor": "",
        "fechaCampaña": "pelado",
        "nroCampo": "34",
        "nombrePreparador": "roberto",
        "preparacionFecha": "12/03/2021",
        "ubicacionFosil": "no se",
        "partesEsqueletales": [
            "",
            "",
            "",
            ""
        ],
        "imagen": "nada",
        "comentario": "eso",
        "URL": "lalala.com"
    },
    {
        "especimenNumero":"3",
        "genero": "Canis",
        "especie": "aureus",
        "periodo": "Jurasio",
        "epoca": "Medio",
        "piso": "3",
        "posicionFilo": [
            "",
            "",
            ""
        ],
        "cuenca": "los morros",
        "formacion": "rio azul",
        "miembro": "craneo",
        "localidad": "san agustin",
        "cordUtm": "",
        "cordGeo": "",
        "campaña": "locardi",
        "descubridor": "",
        "fechaCampaña": "pelado",
        "nroCampo": "34",
        "nombrePreparador": "roberto",
        "preparacionFecha": "12/03/2021",
        "ubicacionFosil": "no se",
        "partesEsqueletales": [
            "",
            "",
            "",
            ""
        ],
        "imagen": "nada",
        "comentario": "eso",
        "URL": "lalala.com"
    },
    {
        "especimenNumero":"4",
        "genero": "Canis",
        "especie": "lupus familiaris",
        "periodo": "Terceario",
        "epoca": "Paleoceno",
        "piso": "3",
        "posicionFilo": [
            "",
            "",
            ""
        ],
        "cuenca": "los morros",
        "formacion": "quebrada vieja",
        "miembro": "craneo",
        "localidad": "san agustin",
        "cordUtm": "",
        "cordGeo": "",
        "campaña": "locardi",
        "descubridor": "",
        "fechaCampaña": "pelado",
        "nroCampo": "34",
        "nombrePreparador": "roberto",
        "preparacionFecha": "12/03/2021",
        "ubicacionFosil": "no se",
        "partesEsqueletales": [
            "",
            "",
            "",
            ""
        ],
        "imagen": "nada",
        "comentario": "eso",
        "URL": "lalala.com"
    },
    {
        "especimenNumero":"5",
        "genero": "Felis",
        "especie": "margarita",
        "periodo": "Terceario",
        "epoca": "Oligoceno",
        "piso": "3",
        "posicionFilo": [
            "",
            "",
            ""
        ],
        "cuenca": "mogna",
        "formacion": "sierras blancas",
        "miembro": "craneo",
        "localidad": "san agustin",
        "cordUtm": "",
        "cordGeo": "",
        "campaña": "locardi",
        "descubridor": "",
        "fechaCampaña": "pelado",
        "nroCampo": "34",
        "nombrePreparador": "roberto",
        "preparacionFecha": "12/03/2021",
        "ubicacionFosil": "no se",
        "partesEsqueletales": [
            "",
            "",
            "",
            ""
        ],
        "imagen": "nada",
        "comentario": "eso",
        "URL": "lalala.com"
    }
]